name: angular_gallery_section
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^4.7.0
  ngdart: ^7.1.1
  ngcomponents: 
    path: ../ngcomponents
  angular_gallery:
    path: ../angular_gallery
  build: ^2.1.1
  build_config: ^1.0.0
  glob: ^2.0.2
  markdown: ^7.0.2
  mustache_template: ^2.0.0
  path: ^1.6.1
  sass: '>=1.15.3 <2.0.0'
  sanitize_html: ^2.0.0