# See https://github.com/google/mono_repo.dart for details
sdk:
  - 2.14.2
  - stable
  - dev

stages:
  - analyze_and_format_core:
    - group:
        - format
        - analyze: .
      sdk:
        - dev
    - group:
        - analyze: .
      sdk:
        - 2.14.2
        - stable
  - unit_test:
    - group:
      - command: ./tool/travis/install_protoc.sh
      - test: --run-skipped
    - group:
      - command: dart run build_runner test -- -p chrome # Chrome already provided by GH Actions

cache:
  directories:
  - .dart_tool
